### ISSUE TITLE
Sub-push service schedule heartbeat checks

### ISSUE THREAD

**Issue by OlegGorj** [OlegGorj/GCP_Chicago_traffic_data#16]

**Comment by OlegGorj** [comment]
```yaml
cron:
- description: "health check with 14 mins intervals"
  url: /_ah/health
  target: push-subscription-worker
  schedule: every 14 minutes
  retry_parameters:
    min_backoff_seconds: 2.5
    max_doublings: 5
```
